server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: log
  rabbitmq:
    host: ${RABBIT_URL:localhost}
    port: ${RABBIT_PORT:5672}
    username: guest
    password: guest