spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432/history}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true